name: 'CI for containers'

on: 
  push:
    branches-ignore:
      - main
    paths:
    - '**/*.Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: development
    steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
