name: 'CI on Push any branch'

on: 
  push:
    branches-ignore:
      - main
    paths-ignore:
    - '**/*.Dockerfile'

jobs:
  conditional-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Skip step for documentation changes
      if: "contains(github.event.head_commit.message, '[skip ci]')"
      run: echo "This step is skipped if the commit message contains '[skip ci]'."
  fail-job:
    runs-on: ubuntu-latest
    #continue-on-error: true
    steps:
    - name: Intentionally fail this job
      run: exit 0 # Change this 
  cleanup:
    needs: fail-job
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running cleanup because build job failed."
  env-if:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Set flag based on secret
        id: set_flag
        run: echo ${{ vars.AWS_REGION }}
      - name: Deploy to Production
        if: ${{ vars.AWS_REGION == 'us-east-2' }}
        run: echo "Deployed from Ohio!"
  producer:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  consumer:
    runs-on: ubuntu-latest
    needs: producer
    steps:
      - env:
          OUTPUT1: ${{needs.producer.outputs.output1}}
          OUTPUT2: ${{needs.producer.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
