name: 'CI on Push and PULL Request merge'

on: 
  #push:
    #branches:
     # - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-test:
    if: github.event.pull_request.merged == true ##
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Build and Test
        run: echo "Running build and test steps"
  deploy: 
    #if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged)
    if: needs.build-and-test.result == 'success'
    needs: build-and-test
    environment: production
    runs-on: ubuntu-latest
    steps: 
    - name: Intro
      run: echo "I'm in PROD $AWS_REGION"
    - name: Checkout code
      uses: actions/checkout@v4.1.1
    - name: Deploy
      run: echo "Running deployment step"
